#####################################
#####     Makefile, level 0     #####
#####################################

hello:
	echo "Hello"
	echo "World!"

# Note: command lines starting with "@" don't echo the command
hello2:
	@echo "Hello"
	@echo "World!"

# Note: commands stop at very first error
error:
	ls /does_not_exist
	echo "this will never be displayed"
